USER-SUPPLIED VALUES:
applicationSet:
  replicas: 1
certificate:
  enabled: true
controller:
  replicas: 1
global:
  domain: argocd.test.com
redis-ha:
  enabled: false
repoServer:
  replicas: 1
server:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    ingressClassName: nginx
    tls: true
