apiVersion: v1
data:
  policy.csv: ""
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2025-09-13T23:32:51Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.1.5
    helm.sh/chart: argo-cd-8.3.7
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "18113"
  uid: 8358180e-3d6b-4a02-9cb3-8d5b2a68c1c3
